### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by sandeepraju** [ElForastero/framer#8]
__What is the issue?__

When you run the project on `yarn watch`, upon update, instead of reloading the project, the application throws the following error

```
(node:40210) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'source' of undefined
    at /Users/janedoe/tmp/framer/node_modules/webpack-manifest-version-sync-plugin/index.js:18:68
    at _next2 (eval at create (/Users/janedoe/tmp/framer/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/janedoe/tmp/framer/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at /Users/janedoe/tmp/framer/node_modules/copy-webpack-plugin/dist/index.js:90:9
(node:40210) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40210) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

__How to reproduce?__

1. Clone the project
2. Install dependencies `yarn install`
3. Build the project `yarn build`
4. Watch the project `yarn watch`
5. Load the unpacked extension on chrome and use the app
6. Now, edit any file to auto-reload the extension (for example, edit `font-size` from `16px` to `26px` in `./src/assets/styles/global.js`)
7. You'll see the above exception stack trace in the terminal.

__What is the expected output?__

Ideally, the application should reload with the new changes and update the files appropriately in the `./build` directory

From my initial debugging, it looks like the there is some issue in using `ExtensionReloader` with `ManifestVersionSyncPlugin`. The path configured in `webpack.config.js` works well when the app starts but upon update to a file and reload, it cannot find the manifest file in the location it looks for.

**Comment by ElForastero** [comment]
Hmm... The `ManifestVersionSyncPlugin` should skip the watch stage of Webpack build.
I'll check it.

https://github.com/ElForastero/webpack-manifest-version-sync-plugin/blob/master/index.js#L15

**Comment by sandeepraju** [comment]
> Hmm... The `ManifestVersionSyncPlugin` should skip the watch stage of Webpack build.
> I'll check it.
> 
> https://github.com/ElForastero/webpack-manifest-version-sync-plugin/blob/master/index.js#L15

Interesting! I think I know what the problem is -- It's using an older version of the plugin: [index.js](https://github.com/ElForastero/webpack-manifest-version-sync-plugin/commit/20e4f8349ce7e51e605a64f6060cead0de7ba9c1#diff-168726dbe96b3ce427e7fedce31bb0bcR13-R32)

Which makes sense! The [package.json](https://github.com/ElForastero/framer/blob/master/package.json#L29) points to version 0.0.1 where as the latest version of it is [v0.0.2](https://www.npmjs.com/package/webpack-manifest-version-sync-plugin/v/0.0.2)

Let me open a PR to update this!

**Comment by sandeepraju** [comment]
@ElForastero Fixed it ^
